### ISSUE TITLE
Disable logs (and changing log levels)

### ISSUE THREAD

**Issue by sqren** [krakenjs/post-robot#11]
tldr: what is the recommended way of disabling logging, and changing log level?

---

I'm trying to disable the log to the browser console. I didn't see any documentation for this - did I miss it?

I'm able to change the log level to 'error' (which is probably a better idea than disabling it entirely). Is this the recommended way of doing it?

```js
var postRobot = require('post-robot');
postRobot.CONFIG.LOG_LEVEL = 'error';
```

Thanks

**Comment by bluepnume** [comment]
Hey, yeah that's correct for now. I can add a `ENABLE_LOGS = false;` if it's sorely needed but I'd recommend at least keeping error logs on.

**Comment by sqren** [comment]
All right. Thanks.
