### ISSUE TITLE
Any interest in supporting tab/windows on same origin with different window hierarchies

### ISSUE THREAD

**Issue by gnz00** [krakenjs/post-robot#13]
Would be great to be able to use the same message bus for syncing across tabs/windows on the same origin without having to provide a window reference.

I know there are a few mechanisms that can be used to implement this: localStorage, SharedWorker, ServiceWorker, WebSocket

Is there any interest? I've implemented this in various forms and would be open to contributing.

**Comment by bluepnume** [comment]
Yeah, definitely sounds like an interesting idea. Maybe some kind of `postRobot.broadcast() / postRobot.subsctibe()` api? Or an extension of `postRobot.send()` so I could just do `postRobot.send('*', 'messagename')`?

Stuff to consider:

- Would be nice to have a way for listeners to get the sending window. Using things like localStorage that could be tricky.

- Would also need to get the original window reference to do things like passing functions, if we want to keep feature-parity with `postRobot.send()`

**Comment by janis91** [comment]
I recently run into the same kind of problem: I tried to test with `top` > `iframe1` > `iframe2` (inside iframe1) and an `iframe3`, which is a direct child of `top`. If you are the one who builds iframe3 and you want it to listen to some messages of iframe2 or the other way.. this would cause a lot of "routing" or "registry / name-reference service" stuff to be available.
Would be a nice enhancement!
