### ISSUE TITLE
Add window validation on send function

### ISSUE THREAD

**Issue by trainerbill** [krakenjs/post-robot#16]
https://github.com/krakenjs/post-robot/blob/master/src/interface/client.js#L112

Was a stupid mistake but i didn't append my iframe to the DOM till after postRobot.send and got an error Expected options.window from the request function.  Would be nice to validate that window is not undefined and maybe some other properties to validate it is an actual window and if not throw a better error.  I'll can submit a PR if you tell me what other properties to validate.

![image](https://cloud.githubusercontent.com/assets/3578259/23523987/7a3a6d48-ff4e-11e6-8349-eaeeb4c06684.png)

**Comment by bluepnume** [comment]
> Would be nice to validate that window is not undefined

That's actually what this error is saying. I guess the message itself could be better. If you'd like to improve it feel free -- the code is just here:

https://github.com/krakenjs/post-robot/blob/master/src/interface/client.js#L16-L18
