### ISSUE TITLE
Unregister postRobot listener

### ISSUE THREAD

**Issue by janis91** [krakenjs/post-robot#20]
I there a way to unregister a specific postRobot listener?
If I am using postRobot in an angular 2 app for example and want to register onto a postMessage, but only if a specific Component is loaded. And I want to unload it if the Component isn't present anymore.

I added the postRobot.on('x') listener but I cannot "destroy" it. 

Is there a way to do this?

Thanks.

**Comment by bluepnume** [comment]
You can do:

```
    var listener = postRobot.on('ON_MESSAGE', { window: window.parent }, function(event) {
      ...
    });

    listener.cancel();
```

I'll add a section for the docs for this too.

**Comment by janis91** [comment]
thanks.

**Comment by samwalshnz** [comment]
I wonder if an API like `postRobot.off('x')` could be suitable?

**Comment by bluepnume** [comment]
@samwalshnz - there's some discussion here about why `off()` isn't offered: https://github.com/krakenjs/post-robot/issues/21#issuecomment-303808080
