### ISSUE TITLE
Unbinding  or .off() ?

### ISSUE THREAD

**Issue by travisdahl** [krakenjs/post-robot#21]
Sorry if this is a silly question or the wrong place to ask it but I was curious, is there a method for unbinding postRobot listeners?

For example:
Previously in my react components I was doing something like...
```
componentWillMount() {
     window.addEventListener('message', this.onMessage);
}

componentWillUnmount() {
    window.removeEventListener('message', this.onMessage);
}
```

Now with `postRobot` I have something like...
```
componentWillMount() {
    postRobot.on('ON_MESSAGE', { window: window.parent }, (event) => {
      this.onMessage(event);
    });
}
```

So i was wondering do I need to unbind? I was imagining something like...
```
componentWillUnmount() {
    postRobot.off('ON_MESSAGE');
}
```

Or is this automatically handled since each request is hashed as a new postMessage?

**Comment by bluepnume** [comment]
You can do:

```
    let listener = postRobot.on('ON_MESSAGE', { window: window.parent }, (event) => {
      this.onMessage(event);
    });

    listener.cancel();
```

I'll add a section for the docs for this too.

**Comment by travisdahl** [comment]
Awesome. Thank you

Would you be opposed to a contribution for an `.off(KEY)` method that takes a key? I feel like it would be a little cleaner API to be able to cancel by key.  I'm willing to give it a shot if it's something you agree with. It can just be a wrapper around the existing `cancel`. 

Thanks for the quick response

**Comment by bluepnume** [comment]
I'd like to understand the use case a bit better first. Generally speaking I prefer not to expose too many interfaces which do the same thing.

**Comment by travisdahl** [comment]
Its super minor but the use case you presented with `let listener = ...` assumed they are both being called in the same scope but in my example/usage I would now need to add a constant or something to the scope of my whole component so it would be available in both the `componentWillMount` and `componentWillUnmount`.  Like I said, its super nit-picky, but it just makes more sense to me that since you always have a unique identifier when you are binding (the key), that you could easily unbind using that same identifier in a similar fashion/pattern.

Also I think as a pattern it just makes more sense, like jQuery [.on()](http://api.jquery.com/on/) and [.off()](http://api.jquery.com/off/) or even the `window.addEventListener` and `window.removeEventListener`.  To undo something in a similar way that you did it in the first place.

If that makes any sense.

**Comment by bluepnume** [comment]
Definitely makes sense. Let me re-open this issue while I mull it over.

**Comment by bluepnume** [comment]
So I'm closing this -- reason is as follows. Listeners aren't just tied to event name, they're tied to [ event name + domain + window ]. So if we were to have a postRobot.off, would it mean "Cancel all event listeners for all domains and all windows for a given name", or only "Cancel all event listeners for the event name with domain * and window *"? 

I think either option leaves a lot of ambiguity, and it's easy enough to implement either outside of postRobot, so I think we're going to stick with the `listener.cancel()` approach to cancel a specific listener.

**Comment by TylerBarnes** [comment]
@travisdahl did you ever figure out a way to scope this to a react component?

I can get it all working except if I call this.listener.cancel() it doesn't do anything. The only way I can make it work is by setting my listener as a global variable and then in my react component I check for listener.cancel and if it exists I call it. Not ideal since I assume adding two instances of this component will mess everything up.

**Comment by TylerBarnes** [comment]
hmm, nevermind! It looks like those "global" variables are still scoped to my component. Not very clean but I don't really care since it seems to work well! Thanks for this library!
