### ISSUE TITLE
Stop distributing .babelrc

### ISSUE THREAD

**Issue by fizker** [krakenjs/post-robot#25]
Your current NPM package includes `.babelrc`, despite being pre-compiled.

This is an issue because webpack/babel in the project using `post-robot` then parses your `.babelrc` and explodes if your required dependencies are not installed.

At the same time, you might want to check the NPM package for other items that might not be interesting, like the setup-files for gulp and eslint.

**Comment by bluepnume** [comment]
Hey you're totally right. Filtering the files has been on my to-do list for a while, but I didn't think about the babelrc issue. I'll strip this out today.

**Comment by bluepnume** [comment]
Can you try now? Should be all good.

**Comment by fizker** [comment]
Sorry, I got distracted. Our build runs without a hitch now 👍
