### ISSUE TITLE
Communication between iframes located in the same window

### ISSUE THREAD

**Issue by nicoferre** [krakenjs/post-robot#26]
We want to send msg between iframes located in the same window, is this supported? We suppose that not because this line: `if (win === window) throw new Error("Attemping to send message to self");`.

Is that correct? In this case, are you working for add this funcionallity?

**Comment by bluepnume** [comment]
You can absolutely send a message to a different frame in the same window.

The reason that error is there is to prevent sending a message **to the current frame/window**. 

Valid: `postRobot.send(window.frames[0], 'foo')`
Invalid: `postRobot.send(window, 'foo')`

In the second case, you're already in the window, so there's no need to send a message to it. Even something like a global function might be preferable.

Does that work for your use-cases?

**Comment by nicolas-t** [comment]
Hello,

When working with webExtensions, in some cases you want to communicate within the same `window`, take a look at the example here : https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#Communicating_with_the_web_page

This paragraph can also be relevant : https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#Content_script_environment

Do you think it's possible to switch from throwing an error to just logging a warning ? 

thanks

**Comment by bluepnume** [comment]
I'm thinking we should just remove that error entirely.
