### ISSUE TITLE
Started to see new console.warn messages

### ISSUE THREAD

**Issue by harouny** [krakenjs/post-robot#30]
This line was added 3 days ago but I'm not sure if that is meant to be a warning or its just left by mistake:
https://github.com/krakenjs/post-robot/blame/1df75d4fdc1ccc08dfdd3170e1d79b97383074e3/src/drivers/listeners.js#L107
```
console.warn('adding request listener:', name); 
```

**Comment by bluepnume** [comment]
Whoops! Published a fix. Gotta add some lint rule to guard against this in future, I'll keep this issue open as a reminder.
