### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by loxy** [krakenjs/post-robot#31]
Are there any typings (TypeScript) or plans to provide them? Can't find anything on that topic...

**Comment by bluepnume** [comment]
We use flow typings in the source code, but right now these aren't externalized in any way. May be a gulp task or something to turn the source-code annotations into a flow/typescript typings file that can be published with /dist. If you want to take a look at adding this, please feel free.

**Comment by loxy** [comment]
I will have a look...

**Comment by loxy** [comment]
Should the typings published under DefinitelyTyped or be part of this repo?

**Comment by haskasu** [comment]
It would be really nice if there is typings .

**Comment by mbenzenhoefer** [comment]
+1

**Comment by jducobu** [comment]
+1

**Comment by NinoScript** [comment]
I'm not planning on making this correct or extensive, nor am I thinking about publishing it under DefinitelyTyped for now, but I'm using this in my project:

https://gist.github.com/NinoScript/6478d60282816393ca75c99937a9f6e5

It may be better than nothing, or at least a starting point.

**Comment by songz** [comment]
should we close this because its a dupe of #89 ?
