### ISSUE TITLE
facing issue in returning response in case error occurred

### ISSUE THREAD

**Issue by SumitAnand7590** [krakenjs/post-robot#38]
My Scenario is like
 I am sending request using postRobot.send from client page
 Capturing request in postRobot.on server page
 Inside postRobot.on calling a function "func xyz()"which returns ajax request/response.
 
So, In my case postRobot is working fine, ajax response is returning back to postRobot.send
But when any error occurs in ajax call or response is coming as a error, I didn't find any way to return that error response back to postRobot.send.

I tried promises but I am getting error in console like ‘Can not reject promise with another promise'.

Please help!!

**Comment by bluepnume** [comment]
Can you share an example of the specific code you're referencing?

**Comment by SumitAnand7590** [comment]
Hey, please check below sample code for reference
## **# Client  page**
```
postRobot.send(window.iframes[0],'getUser',{name:'Jazzz'} ).then(function(event){
    console.log(event.data.name);
}).catch(function(err) {
     console.log('Something went wrong:---' + err.stack);
});
```

## **# Server Page** 
```
postRobot.on('getUser', function(event, callback) {
	return getresponseInfo(event.data).then(function( user ) {
		  var perData = cleanResponseJson(user);
          displayName = perData.displayName;
	  return {
            name: displayName
		};
	});
});

function getresponseInfo(data){
	defer = $.Deferred();
    return $.ajax({
        url: '/xxx/xxx/v3/xxx/@xx?fields=-xxxxxx',
        type: 'GET',
        contentType: 'application/json',
        dataType: 'text',
		success: function (dData) {        
              defer.resolve( dData ); 
		}, error: function (dData) {
		  defer.resolve( dData ); 
		}
	});
}

function cleanResponseJson(user) {
    var s = user;
    var jsonString = s.replace("throw 'allowIllegalResourceCall is false.';", "");
    var json = JSON.parse(jsonString);
    return json;
}
```

In case unautorized access error is occuring but I am not getting error response back at client postRobot.send like I am getting in case of success.

Check below console screen for error scenario

![image](https://user-images.githubusercontent.com/13313180/33168203-1fcff5ee-d00e-11e7-96f6-0f6e817252a6.png)


Thanks!!

**Comment by bluepnume** [comment]
So -- if you make sure you return the latest jQuery version, `jQuery.ajax` will actually return a promise (so no need to ever use `$.Deferred`). Then if you return a rejected promise to post-robot, it will trigger the error handler in the client.

Try something like this: (notice I'm throwing the error again in .catch() so it rejects the promise chain and propagates the error down to the client)

```javascript
postRobot.on('getUser', function(event) {
    return getresponseInfo(event.data).then(function(user) {
        return {
            name: user.displayName
	};
    });
});

function getresponseInfo(data){
    return jQuery.ajax({
        url: '/xxx/xxx/v3/xxx/@xx?fields=-xxxxxx',
        type: 'GET',
        contentType: 'application/json',
        dataType: 'text'
    }).then(function(json) {
        return cleanResponseJson(json);
    }).catch(function(res) {
        var status = res.status || 'unknown';
        var text = res.responseText || '';
        throw new Error('Request failed - status: ' + status + ', ' + text);
    });
}
```

**Comment by SumitAnand7590** [comment]
Its working fine with latest jquery and with above explained approach.
But my problem is 
      I am already using  jQuery v1.x in my application which need to support IE9+ also.
      It will be very difficult to migrate jquery version because it may affect my whole application.

Please suggest possible alternatives with jQuery v1.x version to achieve my scenario.

Thanks

**Comment by bluepnume** [comment]
Glad that solution works in principle!

For what it's worth -- even the latest version of jQuery supports IE9+ -- https://jquery.com/browser-support/

Alternatively -- if you need to coerce a jQuery 1.0 ajax call into a promise, you're welcome to use something like https://github.com/krakenjs/zalgo-promise (this is the promise implementation that post-robot uses internally)

```javascript
function getresponseInfo(data){
    return new ZalgoPromise(function(resolve, reject) {
        jQuery.ajax({
            url: '/xxx/xxx/v3/xxx/@xx?fields=-xxxxxx',
            type: 'GET',
            contentType: 'application/json',
            dataType: 'text',
            success: function(json) {
                resolve(json);
            },
            error: function(res) {
                var status = res.status || 'unknown';
                var text = res.responseText || '';
                reject(new Error('Request failed - status: ' + status + ', ' + text));
            }
        });
    });
}
```

**Comment by SumitAnand7590** [comment]
Thanks for quick reply :) !!!!

Using your latest suggested code for jquery 1.x 
```
function getresponseInfo(data){
    return new ZalgoPromise(function(resolve, reject) {
        jQuery.ajax({
            url: '/xxx/xxx/v3/xxx/@xx?fields=-xxxxxx',
            type: 'GET',
            contentType: 'application/json',
            dataType: 'text',
            success: function(json) {
                resolve(cleanResponseJson(json));
            },
            error: function(res) {
                var status = res.status || 'unknown';
                var text = res.responseText || '';
                reject(new Error('Request failed - status: ' + status + ', ' + text));
            }
        });
    });
}
```

But getting reference error like:
"Error: ReferenceError: ZalgoPromise is not defined at getresponseInfo"

Any idea what I am missing here ???
Do I need to include ZalgoPromise library also apart from postRobot Library ?

Thanks

**Comment by bluepnume** [comment]
Oh yeah, for now you'd need to include something like

`<script src="https://cdn.rawgit.com/krakenjs/zalgo-promise/542b744f/dist/zalgo-promise.min.js"></script>`

**Comment by SumitAnand7590** [comment]
Yeah!!!! Thanks man. It worked.

**Comment by bluepnume** [comment]
Awesome!
