### ISSUE TITLE
The message sent to a sub route in angular application

### ISSUE THREAD

**Issue by cathy02** [krakenjs/post-robot#39]
Try to use post-robot for cross domain storage for Angular application. When adding routes into the application, the message was sent to http://myapp.mydomain.net/search (the default route for my listener application), but the message handler was set on http://myapp.mydomain.net. If I don't use route on my listener application, everything is fine. Any idea on how to solve the problem? Thanks very much.

**Comment by bluepnume** [comment]
I'm not sure I understand the problem. Could you share some simple examples of the code, and any errors you're getting?

**Comment by cathy02** [comment]
Ok, my bad. I setup the listener on another route. Because of Angular's lazy loading, the listener is not created at the time the default route was loaded.
