### ISSUE TITLE
post-robot vs post-robot-ie?

### ISSUE THREAD

**Issue by svenyonson** [krakenjs/post-robot#40]
Request for clarification - the docs don't mention when to use which .js file, but one would assume from the names that the '-ie' variant is specifically for MS IE. However, if I try to run the demo on macOS/Chrome and edit parent/child  to use post-robot.js, it doesn't work (no post button appears on the child window, (empty <body></body>).

I'll just use the '-ie' version but was curious about when each should be used.

**Comment by bluepnume** [comment]
So -- the `.ie` version is only necessary if you want to message between popup windows and your code needs to work in IE. If you're just using iframes, you can use the regular version.

> However, if I try to run the demo on macOS/Chrome and edit parent/child to use post-robot.js, it doesn't work (no post button appears on the child window, (empty ).

Strange. I'll take a look.

**Comment by svenyonson** [comment]
Ah, I figured it out. To use post-robot.js, I had to remove the bridge stuff.

    //postRobot.bridge.openBridge('./bridge.htm', 'mock://foo.com');

    function openWindow() {
	    //window.open('mock://foo.com|./child.htm', Math.random().toString().replace(/[^a-z0-9]+/g, ''));
	    window.open('./child.htm', Math.random().toString().replace(/[^a-z0-9]+/g, ''));
    }

**Comment by bluepnume** [comment]
Aha! Yep
