### ISSUE TITLE
Multiple listeners on the same event

### ISSUE THREAD

**Issue by renanvalentin** [krakenjs/post-robot#48]
Hello!

I would like to have multiple listeners on the same event. e.g:

```javascript
const a = () => {
    channel.on('some:event', event => {
        // do A...
    });
}
```

```javascript
const b = () => {
    channel.on('some:event', event => {
        // do B...
    });
}
```

The above example will thrown an error *Request listener already exists for*. Is this the real intention?

**Comment by bluepnume** [comment]
Yes, this is intended -- since listeners let you return data to the caller, post-robot would have no way to determine which handler to return data from.

```
postRobot.on('getUser', () => 'User A');

postRobot.on('getUser', () => 'User B');
```

```
postRobot.send('getUser').then(({ data }) => console.log(data.user))
```

Does this log `User A` or `User B`?

**Comment by renanvalentin** [comment]
In this case post robot will not work because it will throw an error: [Request listener already exists for ${name} on domain](https://github.com/krakenjs/post-robot/blob/11d6d0e693c8c7b7813b9aedb85cd55ac71ae9db/src/drivers/listeners.js#L156)

I've created an utility function on top of post robot that subscribe once to some event but calls multiple subscribers:

https://gist.github.com/renanvalentin/52d703015205d646b80986b7f13c2d4b

Shall we integrate this into the library ?

**Comment by bluepnume** [comment]
I'd prefer not to integrate this pattern into the library, since post-robot doesn't attempt to be a pub-sub library. It's better to think of listeners as functions that can be registered and called from a remote window. Then the pub-sub mechanism of your choice can be layered on top.

```
postRobot.on('foo', () => pubsub.broadcast('foo'));

pubsub.listen('foo', () => console.log('foo happened!'));
pubsub.listen('foo', () => console.log('foo happened (again)!'));
```

**Comment by renanvalentin** [comment]
Thanks @bluepnume for the explanation!!
