### ISSUE TITLE
PostRobot won't handle ES6 Maps

### ISSUE THREAD

**Issue by GioSensation** [krakenjs/post-robot#49]
PostRobot won't handle ES6 `Map`s correctly. I have spent quite a bit of time looking into this, then found that my data was being lost by postRobot. This is because it uses `JSON.stringify` under the hood, which flattens `Map`s into empty objects (if the `Map` is used correctly, ie. with setters, see [here](https://stackoverflow.com/a/46634512/1948947)).

I believe that this should at least be documented in the readme file, if not properly signalled in the console, otherwise people won't even know what's going wrong.

**Comment by bluepnume** [comment]
Makes sense. Right now I think this should be covered by the serialization section in the readme though, right?

**Comment by GioSensation** [comment]
Yes, but it's not really clear. I bet a simple one-liner would do. Like:

Note that serialization will flatten ES6 `Map`s to an empty object `{}`, so you can't pass them straight into postRobot.

**Comment by bluepnume** [comment]
Sure -- or if you like, you could add it as a supported serialization type here: https://github.com/krakenjs/post-robot/blob/master/src/lib/serialize.js#L124
