### ISSUE TITLE
Clearer documentation and/or examples

### ISSUE THREAD

**Issue by zetlen** [krakenjs/post-robot#5]
I'm really interested in using post-robot for an internal PayPal project (you can Slack me for details), but I don't find the README to be quite clear enough on how to get started. It looks like post-robot is a singleton, but I'm not sure how to establish private two-way communication between a parent a child window. Maybe I am expecting it to work more like [MessageChannel](https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API), and I'm going to plunge ahead and try to implement it anyway, but I think a usage guide and a couple more complete examples would really help.

Thanks!

**Comment by zetlen** [comment]
If I can figure it out by myself, I'd be more than happy to contribute these things.

**Comment by bluepnume** [comment]
Closing this after our discussion. For future readers, if you want to set up a channel just between one window and another:

```javascript
// In the parent window

postRobot.on('foo', { window: childWindow }, ({ source, origin, data }) => {
    ...
});

// In the child window

postRobot.send(window.parent, 'foo').then(({ source, origin, data }) => {
    ...
});
```

@zetlen if you want to make any clarifications to the readme, please feel free 👍
