### ISSUE TITLE
Garbage Collection for sent functions?

### ISSUE THREAD

**Issue by krishan** [krakenjs/post-robot#52]
Thank you for writing this awesome library. 

I have a question though: I understand `post-robot` lets me send functions. 

> post-robot takes the function, and persists it locally in the sending window under a unique id

When does `post-robot` remove a function that has been persisted in this way? AFAIK it has no way of knowing, whether the other window is still referencing the function. 

I looked over the code and found nothing that would ever remove once-persisted functions (only when the other window closes, are all persisted functions removed AFAICS).

If `post-robot` doesn't remove any persisted functions, building an application that sends lots of closures needs to worry about memory bloat. Because all objects reachable from all closures that have ever been sent via `post-robot` would not be GC'ed. At least not, while the other window remains open.

Or am I missing something?

**Comment by bluepnume** [comment]
You're absolutely correct. The only way for us to know for sure is when the window itself is destroyed. So I would avoid sending an unbounded number of functions across the wire.

There may be a good way to implement this using weak maps, which would enable us to detect when a function has been GC'd. But that would need to be conditional on WeakMap support.
