### ISSUE TITLE
support for retry on handshake failure

### ISSUE THREAD

**Issue by zacyang** [krakenjs/post-robot#53]
Hi krakenjs,
I am working on a hybrid project, where we have a react host app hosting an old app (in angular ) in an iframe.

However, the angular app (in the iframe) is a complex application which takes an indefinite time (depends on the client machine and the network) to become fully functional.

It would be nice if post-robot could handle a scenario like.

> postRobot.send(iframe, {data:'hello'}, {timeout: 1000, retry:3});

where `retry` is the max retry( the request will only be sent once).

I could not find any similar functionality in post-robot. And I am happy to create PR for this functionality if it not already been taken care of.

**Comment by bluepnume** [comment]
post-robot should already be waiting for the child frame to send a 'ready' message before it starts sending messages down.

That said, I think the best way to deal with this is to set up a listener in the parent, then message up from the child when it's ready -- and only then start sending messages down. You should be able to achieve this today.

**Comment by zacyang** [comment]
Thanks for your quick response.

Actually, I thought about the approach you mentioned. The thing is, by doing this, we basically make the parent and the child (iframe) to be agnostic to each other (programmatically).

here's the gist of what I am trying to do:

```javascript
const sendReqWithRetry= (targetWindow=this.iframeElm, topic='HANDSHAKE', data={message: 'hello'}, config={responseTimeout: 1000, retryIntervalTime=1000}) => {
        const sendFn = () => postRobot.send(targetWindow, topic, {message: 'hello'}, {timeout: config.responseTimeout});
        sendFn().
        then(function (event) {
            let {message} = event.data;
            console.log(event.source, event.origin, 'got greeting back:', message);
        }).catch((error)=> {
            setTimeout(sendFn, config.retryIntervalTime);
        });
    };
```
