### ISSUE TITLE
No Response from Window - clean up

### ISSUE THREAD

**Issue by alamin3000** [krakenjs/post-robot#54]
Hi I am getting "No Response from Window - clean up" error in my PayPal integration.  I search and can't find the error in google except for one of the source code in this repo.  Can you please let me know what this error means and when it throws this error?

Basically for some customers PayPal window opens for brief time and then closes.  I can't replicate but I know this is happening from my log and also customers are complaining.

Thanks.

**Comment by bluepnume** [comment]
This should be fixed now -- please let me know if you still see it.

**Comment by gragland** [comment]
I'm seeing this issue using the latest version of https://github.com/paypal/paypal-checkout-components from npm (`4.0.304`).

By button is created like so: `paypal.Button.driver('react', { React, ReactDOM })`.

Is there some way to tear-down the button when the parent component unmounts to avoid this issue?

**Comment by luisrudge** [comment]
@bluepnume I'm also seeing this in v4. Is this fixed only in v5?
