### ISSUE TITLE
Cancel function on the event listener

### ISSUE THREAD

**Issue by nosus** [krakenjs/post-robot#59]
If I initialize the listener in this way, `postRobot.listener` and register more than one `on`,
```
var listener = postRobot.listener({ window: childWindow, domain: 'http://zombo.com' });

listener.on('getUser', function(event) {
    return {
        id:   event.data.id,
        name: 'Frodo'
    };
});

listener.on('getManager', function(event) {
    return {
        id:   event.data.id,
        name: 'Erik'
    };
});
```

it would be great if I can simply call 
```
listener.cancel()
```
to cancel all the event listeners, rather than I have to store the listener handler of each `on` function and cancel them one by one.

**Comment by bluepnume** [comment]
Then you might potentially cancel listeners set up by other apps, libraries, etc. It's safer to have you only be able to cancel listeners that you explicitly set up.

**Comment by nosus** [comment]
oh, I get your point, it's fine for me know, I just need to store all the `on` and cancel them. 

Just to discuss a little bit more, I didn't know that when different apps call the `.listern` method they are re-using the same listener object? does it only happen when the `window` and `domain` are the same? 

and then they may possibly overwrite each other's handle function if the event name is the same? or is the `on` method actually is an `add listener` operation? if so, maybe it would also be better if this `.listen` return a unique listener object and add it to an internal `.listener` array of that `window` and `domain`?

**Comment by bluepnume** [comment]
If you try to register a new listener with the same combination of `name` + `window` + `domain`, you'll end up with an exception. The safest bet would be to namespace your messages; `on('myapp:somethinghappened', () => { ... })`

**Comment by nosus** [comment]
sure, of course. Although if this `postRobot.listener({ window: childWindow, domain: 'http://zombo.com' });` can return a unique listener object and add it to an internal `.listener` array, which has that window and domain as the array identifier,  then we can allow the app developer to cancel all the `on` by calling `listern.cancel` and name the event whatever they want without worrying about name conflicts.  

I am not asking for that feature right now, just some thoughts on small things can be improved maybe?  Thank you for asking my questions @bluepnume
