### ISSUE TITLE
eval in post-robot.js

### ISSUE THREAD

**Issue by kabirnig2405** [krakenjs/post-robot#62]
we are using post-robot.js for react chat application, however a csp breach has been reported to us for the use of eval. When we analysed the eval is being used in post-robot.js. we are using post-robot.js as node module, can we fix this in the library so that we can update the module and resolve the CSP issues?? Or is there any other way round for this?? Issue is at Line : 793 post-robot.js.

**Comment by Magneticmagnum** [comment]
FYI, eval() is likely coming from webpack, not this library.  

You can probably find your answer in git webpack repo.

**Comment by bluepnume** [comment]
Yup it's webpack. But we removed it in the latest release.
