### ISSUE TITLE
Expected message to have sourceDomain

### ISSUE THREAD

**Issue by salesfelipe** [krakenjs/post-robot#68]
The newer version of the lib is giving me the following error: 

![image](https://user-images.githubusercontent.com/3926634/49374210-c81ca980-f6e7-11e8-9137-64b27cf25f79.png)

I had to fix the version on "9.0.0" so it would come back working again, didn't find any help on the docs.

**Comment by TylerBarnes** [comment]
I'm having the same issue

**Comment by TylerBarnes** [comment]
Figured it out! You just have to update post-robot.js wherever the inside of your iframe is.

**Comment by bluepnume** [comment]
Yup, ideally need to make sure the version matches between windows. 👍
