### ISSUE TITLE
Illegal modification of built-in Buffer class

### ISSUE THREAD

**Issue by heri16** [krakenjs/post-robot#69]
Uncaught TypeError: Cannot assign to read only property 'toString' of object '[object Object]'

```javascript
Buffer.prototype.toString = function toString () {
  var length = this.length | 0
  if (length === 0) return ''
  if (arguments.length === 0) return utf8Slice(this, 0, length)
  return slowToString.apply(this, arguments)
}
```

Seems to be conflicting with a browser security extension.

**Comment by bluepnume** [comment]
Are you sure you're looking at the right library? Can you point our where you see this code?

**Comment by heri16** [comment]
Apologies, seems like Webpack v4 acting strange only with new postRobot versions and injecting its Buffer polyfills for post-robot.js . Did not manage to find out why webpack is doing this.

https://webpack.js.org/configuration/node/

Fixed with:
```
// webpack.config.js
{
  node: false
}
```
