### ISSUE TITLE
Enforce Security by default

### ISSUE THREAD

**Issue by vertex** [krakenjs/post-robot#7]
Can we make the domain configuration item a mandatory configuration that occurs before init?  I think this is really important, as it can really cause a lot of malicious issues if people use it and don't maintain it.

**Comment by bluepnume** [comment]
I'm contemplating making the `domain` option default to the current domain. This seems to give us the best of both worlds: users messaging between same-domain windows don't need to add extra boilerplate, and everyone else has to explicitly pass a `domain`. Sound ok?
