### ISSUE TITLE
Uncaught Error: Target window is closed

### ISSUE THREAD

**Issue by SteffenDE** [krakenjs/post-robot#70]
I just tried updating from post-robot 9.0.35 to 10.0.1 and communication fails with a "Target window is closed" exception in Chrome 71.
The relevant code section is https://github.com/krakenjs/cross-domain-utils/blob/2f9d27f602d697ace680dc7fadf09e25f0ec8389/src/utils.js#L505. top and parent do not exist on the win variable.

```html
<!DOCTYPE html>
<html>
<head>
	<title>client.html</title>
	<style type="text/css">
		html, body, iframe {
			width: 100%;
			height: 100%;
			padding: 0;
			margin: 0;
			border: none;
		}
	</style>
</head>
<body>
<iframe src="extension.html"></iframe>
<script type="text/javascript" src="https://unpkg.com/post-robot@10.0.1/dist/post-robot.js"></script>
<script type="text/javascript">
	postRobot.send(document.getElementsByTagName("iframe")[0], "getInfo", null, { domain: "*" }).then(function(event) {
		console.log("Extension sent info", event);
	});
	setTimeout(() => postRobot.send(document.getElementsByTagName("iframe")[0], "data", {}, { domain: "*" }), 500);
</script>
</body>
</html>
```

```html
<!DOCTYPE html>
<html>
<head>
	<title>extension.html</title>
	<style type="text/css">
		html, body, div, iframe {
			width: 100%;
			height: 100%;
			margin: 0;
			padding: 0;
			border: none;
		}
	</style>
</head>
<body>
	<script type="text/javascript" src="https://unpkg.com/post-robot@10.0.1/dist/post-robot.js"></script>
	<script type="text/javascript">
		postRobot.on("data", function(event) {
			console.log("received data", event.data);
		});
	</script>
</body>
</html>
```

**Comment by bluepnume** [comment]
Can you do: `document.getElementsByTagName("iframe")[0].contentWindow`

**Comment by SteffenDE** [comment]
<img width="1190" alt="bildschirmfoto 2019-02-06 um 23 15 06" src="https://user-images.githubusercontent.com/4116351/52377408-1a21d880-2a65-11e9-8dc6-a77fb5e6d9d9.png">

The same code works completely fine with post-robot@9.0.36.

**Comment by bluepnume** [comment]
You changed `document.getElementsByTagName("iframe")[0]` in your code to `document.getElementsByTagName("iframe")[0].contentWindow` right?

What happens when you log `document.getElementsByTagName("iframe")[0].contentWindow.top` or `document.getElementsByTagName("iframe")[0].contentWindow.parent`?

**Comment by SteffenDE** [comment]
Oh, that did it! Seems like 9.0 accepts iframes while 10.0 needs an actual window.
Sorry for bothering! Is there some kind of changelog with breaking changes for new versions?

**Comment by bluepnume** [comment]
No problem! I definitely need to get around to adding an automatic changelog. That's definitely a big gap right now so sorry for the pain.
