### ISSUE TITLE
Disable logs in v10

### ISSUE THREAD

**Issue by dackmin** [krakenjs/post-robot#71]
Is there any particular reason `CONFIG` is not available anymore inside the `postRobot` object?

```javascript
postRobot.CONFIG.LOG_LEVEL = 'disabled';
```
--> Is now making our tests fail

We used it to disable logs completely on production environments because there were some remaining error logs that we were already catching and processing our own way.

Is there a way we can achieve the same behavior in v10?

**Comment by bluepnume** [comment]
Logs should be disabled by default in the v10 build now. Do you see any coming through?

**Comment by dackmin** [comment]
Yep they're gone in v10, thanks 👍 
It wasn't really clear in the commits. Will it be possible to add a changelog listing the major changes starting with v10? To avoid opening useless issues like this one 😄

**Comment by harshes53** [comment]
@bluepnume Is there a way to turn on debug mode when in development?
