### ISSUE TITLE
Add breaking changes in release notes

### ISSUE THREAD

**Issue by dackmin** [krakenjs/post-robot#72]
As I stated in another issue (#71), some breaking changes have been shipped with v10 but are not mentioned anywhere, such as:

- `postRobot.CONFIG` not existing anymore (breaking builds if you used to disable logs using `postRobot.CONFIG.LOG_LEVEL`)
- `.send()` now only accepting a `window` object instead of an `iframe`, also breaking tests (induced by https://github.com/krakenjs/post-robot/commit/675ddec541013b4ed5cbda0b4e6ba6a499193076#diff-bf171c73c84cd3085514c56671eb2a5cL1)

It would be great to add a list of breaking changes made between two major releases :)

**Comment by GioSensation** [comment]
I strongly support this proposal.

**Comment by barnesicle** [comment]
`postRobot.CONFIG.LOG_LEVEL` was removed. How do you change log levels now?

**Comment by barnesicle** [comment]
In additional to my question above, from what I can see, functions client() and listener() were also removed? Is there a reason why they were?

**Comment by bluepnume** [comment]
There should only be logs in debug mode now. By default that's off, so you shouldn't see any logs. I probably need to set up a webpack build to generate a dev bundle with debug mode, for local testing.

The latest release attempts to simplify the public interface of post-robot a fair bit. `on` and `send` should cover every possible use case. Please let me know if you find something they don't cover.

**Comment by bluepnume** [comment]
Agreed on the proposal for a changelog 👍
