### ISSUE TITLE
Permission denied to access object on Firefox

### ISSUE THREAD

**Issue by jducro** [krakenjs/post-robot#78]
When I try to use `post-robot` with firefox I get this error:
```
Error: postrobot_message_ack postrobot_ready error:
  - postrobot_post_message: Permission denied to access object
```

<img width="1110" alt="Screenshot 2019-04-17 at 12 02 51" src="https://user-images.githubusercontent.com/898196/56279636-c7ba0380-6108-11e9-828f-e08ae0962340.png">

Things works fine with Chrome.

Any idea how I could debug that?

Thanks

**Comment by jducro** [comment]
Here's where I use post-robot:
https://github.com/deskpro/apps-libs/blob/master/packages/apps-sdk/src/Widget/WidgetWindowBridge.js#L202

**Comment by jcubic** [comment]
Not sure if this is related, but I've found that iframe for Cross-Domain localStorage require to have CORS enabled on Firefox, I have no idea why. I've written that in this article: [Cross-Domain LocalStorage](https://jcubic.wordpress.com/2014/06/20/cross-domain-localstorage/).

**Comment by mnicpt** [comment]
@jducro Have you tried enabling CORS as @jcubic has mentioned?  It doesn't surprise me that Firefox is requiring that.  Let me know if it works for.  If it doesn't, we can dig a bit more.

**Comment by jducro** [comment]
@mnicpt the project this was used in is deprecated, I can't test that anymore, I'll close the issue.
