### ISSUE TITLE
Cross domain, with 3rd party cookies blocked.

### ISSUE THREAD

**Issue by ydennisy** [krakenjs/post-robot#80]
Hello,
So it seems this does not work when users block 3rd party tracking - is there any proposed workarounds?
I actually have my SDK on two web domains and need for them to share a state - any suggestions?

**Comment by jcubic** [comment]
It seems that this is not possible. But I would like to know if there is some workaround. I have similar project [sysend.js](https://github.com/jcubic/sysend.js), and have the same issue. Cross-Domain don't work on Safari when 3rd party tracking is blocking is enabled.

**Comment by mnicpt** [comment]
@ydennisy Sorry this is now just being addressed.  @jcubic You're correct.  This will not work when 3rd party tracking is blocked and unfortunately it is blocked by default on Safari.  I am not aware of a workaround.  Thanks for responding @jcubic .  I'm going to close this.  If either of you would like this be be re-opened, please let me know.

**Comment by jcubic** [comment]
I've just added a note in Readme so anyone knows that this doesn't work in Safari. Found this in some other project that uses LS (found link on StackOverflow).
