### ISSUE TITLE
Postrobot fails after 2000ms because of failed ack sending

### ISSUE THREAD

**Issue by ffbesnikcelaj** [krakenjs/post-robot#81]
It seems like the communication between a window that uses version 10.0.14 and one that uses 10.0.18 doesn't work.
An error occurs that says: "ERROR Error: No ack for postMessage XXXX in
https://localhost:3000 in 2000ms" when i try to send a message from the higher version to the lower one.
 I downgraded the higher version to 10.0.14 and it worked. Seems like there is some Breaking Behavior in between those versions.

**Comment by peteringram0** [comment]
Also getting this. Downgrade to 10.0.14 fixed for me also.

**Comment by droidenator** [comment]
I did some debugging on this issue and it appears to occur anytime you have a version mis-match. That is, both windows should use the same version. If the versions match, you should be able to use the latest version without issue.

**Comment by mstuart** [comment]
Sorry for the late reply. We're ramping up support for our open-source repos. Feel free to re-open this if @droidenator's suggestion doesn't work for you. Thanks!

**Comment by giscafer** [comment]
> different version

this waste me a lot time!!!!!
