### ISSUE TITLE
Uncaught DOMException: Blocked a frame with origin "<origin name>" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by tenjojeremy** [krakenjs/post-robot#83]
![InkedBeta_LI](https://user-images.githubusercontent.com/25231946/63779739-476c9180-c8a4-11e9-89de-11462ea64bb4.jpg)

Thank you

**Comment by bluepnume** [comment]
Hi, did you figure this one out? If not, do you have a url where I can reproduce the issue?

**Comment by tenjojeremy** [comment]
I used Zoid instead of post-robot to handle communication between the first party local storage and the windows local storage. Sorry I can't share the code as it's not owned by me.
