### ISSUE TITLE
Create TypeScript typings

### ISSUE THREAD

**Issue by mstuart** [krakenjs/post-robot#89]
See https://github.com/krakenjs/post-robot/issues/31 for more information.

This project isn't written in TypeScript, but many TypeScript users would like to use published typings. For this issue, create TypeScript typings that cover the exported functions, and contribute it back to DefinitelyTyped!

This issue is great for someone who wants to learn more about TypeScript!

**Comment by JohnnyUrosevic** [comment]
Hi I would to work on this to learn a little bit about TypeScript :)

**Comment by mstuart** [comment]
Hi @JohnnyUrosevic! Still want to take this? Just checking in, so that we can give others a chance if you're busy. Thanks!

**Comment by JohnnyUrosevic** [comment]
Hi I still want to work on this, but I'm just a Typescript noob so I'm not exactly sure where to start

**Comment by Cijin** [comment]
Hi, if this issue is still open. I'd like to take this up.

**Comment by JohnnyUrosevic** [comment]
go ahead and take it @Cijin

**Comment by Cijin** [comment]
Thanks, on it :+1:

**Comment by songz** [comment]
Starting point, from #31 that someone did: https://gist.github.com/NinoScript/6478d60282816393ca75c99937a9f6e5

**Comment by Cijin** [comment]
@mstuart  PR created at definitely typed. The owners of the package will be notified automatically by the typescript bot.

[Here is the link to the PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48769)

**Comment by mstuart** [comment]
Sweet!! Thanks @Cijin!

**Comment by songz** [comment]
@mstuart should this issue be closed? Seems like all the functions that postrobot exposes are closed.

**Comment by mstuart** [comment]
I think so! Thanks for keeping an eye on that @songz!
